2025-05-27 13:11:43,823 [INFO] MurmurNet.ConfigManager: 設定ファイルを発見: C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\config.yaml
2025-05-27 13:11:43,831 [INFO] MurmurNet.ConfigManager: 設定ファイルを読み込みました: C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\config.yaml
2025-05-27 13:11:43,831 [INFO] MurmurNet.ConfigManager: 設定のバリデーションが完了しました
2025-05-27 13:11:47,299 [INFO] root: 設定されたモデルを使用します: llama
2025-05-27 13:11:47,364 [INFO] sentence_transformers.SentenceTransformer: Use pytorch device_name: cpu
2025-05-27 13:11:47,364 [INFO] sentence_transformers.SentenceTransformer: Load pretrained SentenceTransformer: all-MiniLM-L6-v2
2025-05-27 13:11:51,294 [ERROR] __main__: プロセス並列テスト failed: cannot import name 'ProcessCoordinator' from 'MurmurNet.modules.process_coordinator' (C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\MurmurNet\modules\process_coordinator.py)
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\MurmurNet\test_script.py", line 146, in run_test_category
    await test_method()
  File "C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\MurmurNet\test_script.py", line 270, in run_process_parallel_tests
    from MurmurNet.modules.process_agent_manager import ProcessAgentManager
  File "C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\MurmurNet\modules\process_agent_manager.py", line 19, in <module>
    from MurmurNet.modules.process_coordinator import ProcessCoordinator
ImportError: cannot import name 'ProcessCoordinator' from 'MurmurNet.modules.process_coordinator' (C:\Users\admin\Desktop\課題研究\ワークスペース\MurmurNet\MurmurNet\modules\process_coordinator.py)
